import { FormConfig } from '@/types';

export function generateJVZooPHP(config: FormConfig): string {
    const productsOptions = config.products.map(p =>
        `                    <option value="${p.itemNumber}">${p.name}</option>`
    ).join('\n');

    return `<?php
// ${config.formTitle} - JVZoo Integration
// Generated by FormForge

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $_POST['ctranstime'] = time();
    
    if (empty($_POST['ccustname']) || empty($_POST['ccustemail']) || empty($_POST['ctransreceipt'])) {
        die('Error: All fields are required.');
    }
    
    if (!filter_var($_POST['ccustemail'], FILTER_VALIDATE_EMAIL)) {
        die('Error: Invalid email address.');
    }
    
    $postData = [
        'caffitid' => $_POST['caffitid'] ?? '',
        'ccustcc' => $_POST['ccustcc'] ?? 'US',
        'ccuststate' => $_POST['ccuststate'] ?? '',
        'cprodtitle' => $_POST['cprodtitle'] ?? '${config.productTitle}',
        'cprodtype' => $_POST['cprodtype'] ?? 'STANDARD',
        'ctransaction' => $_POST['ctransaction'] ?? 'SALE',
        'ctransaffiliate' => $_POST['ctransaffiliate'] ?? '',
        'ctransamount' => $_POST['ctransamount'] ?? '${config.jvzooConfig?.transAmount || "37.00"}',
        'ctranspaymentmethod' => $_POST['ctranspaymentmethod'] ?? '${config.jvzooConfig?.paymentMethod || "PYPL"}',
        'ctranstime' => $_POST['ctranstime'],
        'ctransvendor' => $_POST['ctransvendor'] ?? '${config.jvzooConfig?.vendorId || ""}',
        'cupsellreceipt' => $_POST['cupsellreceipt'] ?? '',
        'cvendthru' => $_POST['cvendthru'] ?? '',
        'cverify' => $_POST['cverify'] ?? '${config.jvzooConfig?.verifyCode || ""}',
        'ccustname' => $_POST['ccustname'],
        'ccustemail' => $_POST['ccustemail'],
        'ctransreceipt' => $_POST['ctransreceipt'],
        'cproditem' => $_POST['cproditem']
    ];
    
    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, '${config.submitEndpoint}');
    curl_setopt($ch, CURLOPT_POST, true);
    curl_setopt($ch, CURLOPT_POSTFIELDS, http_build_query($postData));
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);
    curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
    
    $response = curl_exec($ch);
    $httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);
    
    if ($httpCode === 200) {
        echo json_encode(['status' => 'success', 'message' => 'Form submitted successfully!']);
    } else {
        echo json_encode(['status' => 'error', 'message' => 'Submission failed. Please try again.']);
    }
    exit;
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${config.formTitle}</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body {
            font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            background: ${config.theme === 'dark' ? 'linear-gradient(135deg, #0a0a0a 0%, #1a1a2e 100%)' : 'linear-gradient(135deg, #f5f5f5 0%, #e8e8e8 100%)'};
            min-height: 100vh;
            display: flex;
            align-items: center;
            justify-content: center;
            padding: 20px;
        }
        .form-container {
            background: ${config.theme === 'dark' ? 'rgba(20, 20, 30, 0.95)' : 'rgba(255, 255, 255, 0.98)'};
            backdrop-filter: blur(20px);
            border-radius: 24px;
            box-shadow: 0 25px 80px rgba(0, 0, 0, ${config.theme === 'dark' ? '0.5' : '0.15'});
            padding: 48px;
            width: 100%;
            max-width: 520px;
            border: 1px solid ${config.theme === 'dark' ? 'rgba(255,255,255,0.1)' : 'rgba(0,0,0,0.05)'};
            position: relative;
            overflow: hidden;
        }
        .form-container::before {
            content: '';
            position: absolute;
            top: 0;
            left: 0;
            right: 0;
            height: 4px;
            background: linear-gradient(90deg, ${config.primaryColor}, ${config.accentColor});
        }
        .form-title {
            text-align: center;
            margin-bottom: 6px;
            color: ${config.theme === 'dark' ? '#ffffff' : '#1a1a1a'};
            font-size: 24px;
            font-weight: 700;
            letter-spacing: -0.5px;
        }
        .form-subtitle {
            text-align: center;
            margin-bottom: 28px;
            color: ${config.theme === 'dark' ? 'rgba(255,255,255,0.6)' : 'rgba(0,0,0,0.5)'};
            font-size: 13px;
        }
        .form-group { margin-bottom: 24px; }
        .form-label {
            display: block;
            margin-bottom: 6px;
            color: ${config.theme === 'dark' ? 'rgba(255,255,255,0.8)' : '#333'};
            font-weight: 600;
            font-size: 12px;
        }
        .form-input, .form-select {
            width: 100%;
            padding: 12px 16px;
            border: 2px solid ${config.theme === 'dark' ? 'rgba(255,255,255,0.1)' : '#e0e0e0'};
            border-radius: 12px;
            font-size: 14px;
            color: ${config.theme === 'dark' ? '#ffffff' : '#1a1a1a'};
            background: ${config.theme === 'dark' ? 'rgba(255,255,255,0.05)' : '#fafafa'};
            transition: all 0.3s ease;
            outline: none;
            font-family: inherit;
        }
        .form-input:focus, .form-select:focus {
            border-color: ${config.primaryColor};
            box-shadow: 0 0 0 4px ${config.primaryColor}20;
        }
        .form-input::placeholder {
            color: ${config.theme === 'dark' ? 'rgba(255,255,255,0.4)' : 'rgba(0,0,0,0.4)'};
        }
        .form-select option {
            background: ${config.theme === 'dark' ? '#1a1a2e' : '#ffffff'};
            color: ${config.theme === 'dark' ? '#ffffff' : '#1a1a1a'};
            padding: 12px;
        }
        .submit-btn {
            width: 100%;
            padding: 14px 32px;
            background: ${config.buttonStyle === 'gradient'
            ? `linear-gradient(135deg, ${config.primaryColor} 0%, ${config.accentColor} 100%)`
            : config.buttonStyle === 'outline' ? 'transparent' : config.primaryColor};
            color: ${config.buttonStyle === 'outline' ? config.primaryColor : '#ffffff'};
            border: ${config.buttonStyle === 'outline' ? `2px solid ${config.primaryColor}` : 'none'};
            border-radius: 12px;
            font-size: 14px;
            font-weight: 600;
            cursor: pointer;
            transition: all 0.3s ease;
            font-family: inherit;
            margin-top: 8px;
        }
        .submit-btn:hover {
            transform: translateY(-2px);
            box-shadow: 0 10px 40px ${config.primaryColor}40;
        }
        .submit-btn:disabled {
            opacity: 0.7;
            cursor: not-allowed;
            transform: none;
        }
        .message {
            padding: 16px 20px;
            border-radius: 12px;
            margin-bottom: 24px;
            text-align: center;
            font-weight: 500;
            display: none;
        }
        .message.success { background: rgba(34, 197, 94, 0.15); color: #22c55e; border: 1px solid rgba(34, 197, 94, 0.3); }
        .message.error { background: rgba(239, 68, 68, 0.15); color: #ef4444; border: 1px solid rgba(239, 68, 68, 0.3); }
        .generate-link {
            display: block;
            text-align: right;
            color: ${config.primaryColor};
            text-decoration: none;
            font-size: 13px;
            margin-top: 6px;
            cursor: pointer;
            font-weight: 500;
        }
        .generate-link:hover { text-decoration: underline; }
    </style>
</head>
<body>
    <div class="form-container">
        <h1 class="form-title">${config.formTitle}</h1>
        <p class="form-subtitle">Complete your registration below</p>
        <div id="message" class="message"></div>
        
        <form id="registrationForm" method="POST">
            <input type="hidden" name="caffitid" value="">
            <input type="hidden" name="ccustcc" value="US">
            <input type="hidden" name="ccuststate" value="">
            <input type="hidden" name="cprodtitle" id="cprodtitle2" value="${config.productTitle}">
            <input type="hidden" name="cprodtype" value="STANDARD">
            <input type="hidden" name="ctransaction" value="SALE">
            <input type="hidden" name="ctransaffiliate" value="">
            <input type="hidden" name="ctransamount" value="${config.jvzooConfig?.transAmount || "37.00"}">
            <input type="hidden" name="ctranspaymentmethod" value="${config.jvzooConfig?.paymentMethod || "PYPL"}">
            <input type="hidden" name="ctranstime" value="">
            <input type="hidden" name="ctransvendor" value="${config.jvzooConfig?.vendorId || ""}">
            <input type="hidden" name="cupsellreceipt" value="">
            <input type="hidden" name="cvendthru" value="">
            <input type="hidden" name="cverify" value="${config.jvzooConfig?.verifyCode || ""}">
            
            <div class="form-group">
                <label class="form-label" for="name">Full Name</label>
                <input type="text" name="ccustname" id="name" class="form-input" placeholder="Enter your full name" required>
            </div>
            
            <div class="form-group">
                <label class="form-label" for="email">Email Address</label>
                <input type="email" name="ccustemail" id="email" class="form-input" placeholder="Enter your email address" required>
            </div>
            
            <div class="form-group">
                <label class="form-label" for="transaction">Transaction ID</label>
                <input type="text" name="ctransreceipt" id="transaction" class="form-input" placeholder="Enter your transaction ID" required>
                <a href="javascript:void(0);" id="generateBtn" class="generate-link">Generate Transaction ID →</a>
            </div>
            
            <div class="form-group">
                <label class="form-label" for="product">Select Product</label>
                <select name="cproditem" id="product" class="form-select" required>
                    <option value="">Choose a product...</option>
${productsOptions}
                </select>
            </div>
            
            <button type="submit" class="submit-btn">Complete Registration</button>
        </form>
    </div>

    <script>
        function generateTransactionID() {
            const digits = '0123456789';
            const letters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
            const firstDigit = Math.floor(Math.random() * 9) + 1;
            const secondChar = letters[Math.floor(Math.random() * letters.length)];
            let middleDigits = '';
            for (let i = 0; i < 7; i++) middleDigits += digits[Math.floor(Math.random() * digits.length)];
            const thirdChar = letters[Math.floor(Math.random() * letters.length)];
            let lastDigits = '';
            for (let i = 0; i < 6; i++) lastDigits += digits[Math.floor(Math.random() * digits.length)];
            const lastChar = letters[Math.floor(Math.random() * letters.length)];
            return firstDigit + secondChar + middleDigits + thirdChar + lastDigits + lastChar;
        }

        document.getElementById('generateBtn').addEventListener('click', function(e) {
            e.preventDefault();
            document.getElementById('transaction').value = generateTransactionID();
        });

        document.getElementById('registrationForm').addEventListener('submit', function(e) {
            e.preventDefault();
            const form = this;
            const btn = form.querySelector('.submit-btn');
            const message = document.getElementById('message');
            
            btn.disabled = true;
            btn.textContent = 'Processing...';
            message.style.display = 'none';
            
            form.querySelector('input[name="ctranstime"]').value = Math.floor(Date.now() / 1000);
            
            fetch(window.location.href, {
                method: 'POST',
                body: new FormData(form)
            })
            .then(response => response.json())
            .then(data => {
                message.style.display = 'block';
                message.className = 'message ' + (data.status === 'success' ? 'success' : 'error');
                message.textContent = data.message;
                if (data.status === 'success') form.reset();
            })
            .catch(() => {
                message.style.display = 'block';
                message.className = 'message error';
                message.textContent = 'An error occurred. Please try again.';
            })
            .finally(() => {
                btn.disabled = false;
                btn.textContent = 'Complete Registration';
            });
        });
        
        document.getElementById('product').addEventListener('change', function() {
            if (this.value) {
                document.getElementById('cprodtitle2').value = this.options[this.selectedIndex].text;
            }
        });
    </script>
</body>
</html>`;
}
