import { FormConfig } from '@/types';

export function generateWarriorPlusPHP(config: FormConfig): string {
    const productsOptions = config.products.map(p =>
        `                    <option value="${p.itemNumber}">${p.name}</option>`
    ).join('\n');

    return `<?php
// ${config.formTitle} - WarriorPlus Integration
// Generated by FormForge

$success = null;
$message = '';

if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['submit_form'])) {
    if (empty($_POST['WP_BUYER_NAME']) || empty($_POST['WP_BUYER_EMAIL']) || empty($_POST['WP_ITEM_NUMBER'])) {
        $success = false;
        $message = 'Error: All fields are required.';
    } elseif (!filter_var($_POST['WP_BUYER_EMAIL'], FILTER_VALIDATE_EMAIL)) {
        $success = false;
        $message = 'Error: Invalid email address.';
    } else {
        $postData = array(
            'WP_ITEM_NAME' => '${config.productTitle}',
            'cprodtype' => 'BUNDLE',
            'WP_ACTION' => 'SALE',
            'WP_SALE_AMOUNT' => '',
            'WP_PAYMETHOD' => 'PYPL',
            'WP_TXNID' => '${config.warriorplusConfig?.txnId || "8AB94645KS7334044"}',
            'WP_SALEID' => '${config.warriorplusConfig?.saleId || "8AB94645KS7334044"}',
            'WP_PAYMENT_STATUS' => 'Completed',
            'WP_SECURITYKEY' => '${config.warriorplusConfig?.securityKey || ""}',
            'cverify' => '56FD9600',
            'WP_BUYER_NAME' => $_POST['WP_BUYER_NAME'],
            'WP_BUYER_EMAIL' => $_POST['WP_BUYER_EMAIL'],
            'WP_ITEM_NUMBER' => $_POST['WP_ITEM_NUMBER']
        );
        
        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL, '${config.submitEndpoint}');
        curl_setopt($ch, CURLOPT_POST, true);
        curl_setopt($ch, CURLOPT_POSTFIELDS, http_build_query($postData));
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
        
        $response = curl_exec($ch);
        $httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
        curl_close($ch);
        
        if ($httpCode === 200) {
            $success = true;
            $message = "Registration successful! Your account is ready.";
        } else {
            $success = false;
            $message = "There was an error processing your request. Please try again.";
        }
    }
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${config.formTitle}</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet">
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        
        @keyframes fadeIn {
            from { opacity: 0; transform: translateY(20px); }
            to { opacity: 1; transform: translateY(0); }
        }
        
        @keyframes pulse {
            0%, 100% { box-shadow: 0 0 0 0 ${config.primaryColor}40; }
            50% { box-shadow: 0 0 0 15px ${config.primaryColor}00; }
        }
        
        body {
            background: ${config.theme === 'dark'
            ? `linear-gradient(180deg, #0a0a0a 0%, #1a0a0a 50%, #0a0a0a 100%)`
            : `linear-gradient(180deg, #f8f9fa 0%, #ffffff 50%, #f8f9fa 100%)`};
            color: ${config.theme === 'dark' ? '#ffffff' : '#1a1a1a'};
            font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            min-height: 100vh;
            display: flex;
            align-items: center;
            justify-content: center;
            padding: 20px;
        }
        
        .form-container {
            background: ${config.theme === 'dark'
            ? 'linear-gradient(135deg, rgba(20, 20, 20, 0.98), rgba(30, 20, 25, 0.98))'
            : 'linear-gradient(135deg, rgba(255, 255, 255, 0.98), rgba(250, 250, 250, 0.98))'};
            backdrop-filter: blur(20px);
            padding: 50px;
            border-radius: 24px;
            box-shadow: 0 50px 100px rgba(0, 0, 0, ${config.theme === 'dark' ? '0.6' : '0.12'});
            width: 100%;
            max-width: 580px;
            border: 2px solid ${config.primaryColor}30;
            animation: fadeIn 0.6s ease-out;
            position: relative;
            overflow: hidden;
        }
        
        .form-container::before {
            content: '';
            position: absolute;
            top: 0;
            left: 0;
            right: 0;
            height: 5px;
            background: linear-gradient(90deg, ${config.primaryColor}, ${config.accentColor});
        }
        
        .header-section {
            text-align: center;
            margin-bottom: 40px;
        }
        
        .form-icon {
            width: 80px;
            height: 80px;
            background: linear-gradient(135deg, ${config.primaryColor}, ${config.accentColor});
            border-radius: 20px;
            display: inline-flex;
            align-items: center;
            justify-content: center;
            font-size: 40px;
            margin-bottom: 20px;
            box-shadow: 0 15px 40px ${config.primaryColor}40;
        }
        
        .form-title {
            font-size: 28px;
            font-weight: 800;
            background: linear-gradient(135deg, ${config.primaryColor}, ${config.accentColor});
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
            background-clip: text;
            margin-bottom: 8px;
            letter-spacing: -0.5px;
        }
        
        .form-subtitle {
            font-size: 13px;
            color: ${config.theme === 'dark' ? 'rgba(255,255,255,0.6)' : 'rgba(0,0,0,0.5)'};
            font-weight: 500;
        }
        
        .form-group { margin-bottom: 24px; }
        
        .form-label {
            display: block;
            margin-bottom: 8px;
            font-weight: 600;
            color: ${config.theme === 'dark' ? 'rgba(255,255,255,0.85)' : '#333'};
            font-size: 12px;
            text-transform: uppercase;
            letter-spacing: 0.5px;
        }
        
        .form-input, .form-select {
            width: 100%;
            padding: 14px 18px;
            background: ${config.theme === 'dark' ? 'rgba(0, 0, 0, 0.4)' : 'rgba(255, 255, 255, 0.8)'};
            border: 2px solid ${config.theme === 'dark' ? 'rgba(255,255,255,0.1)' : '#e5e5e5'};
            border-radius: 14px;
            color: ${config.theme === 'dark' ? '#ffffff' : '#1a1a1a'};
            font-size: 14px;
            transition: all 0.3s ease;
            font-family: inherit;
        }
        
        .form-input:focus, .form-select:focus {
            outline: none;
            border-color: ${config.primaryColor};
            box-shadow: 0 0 0 4px ${config.primaryColor}15;
        }

        .form-input::placeholder {
            color: ${config.theme === 'dark' ? 'rgba(255,255,255,0.4)' : 'rgba(0,0,0,0.4)'};
        }

        .form-select option {
            background: ${config.theme === 'dark' ? '#1a1a2e' : '#ffffff'};
            color: ${config.theme === 'dark' ? '#ffffff' : '#1a1a1a'};
            padding: 12px;
        }
        
        .submit-btn {
            width: 100%;
            padding: 16px;
            background: ${config.buttonStyle === 'gradient'
            ? `linear-gradient(135deg, ${config.primaryColor}, ${config.accentColor})`
            : config.buttonStyle === 'outline' ? 'transparent' : config.primaryColor};
            color: ${config.buttonStyle === 'outline' ? config.primaryColor : (config.theme === 'dark' ? '#000000' : '#ffffff')};
            border: ${config.buttonStyle === 'outline' ? `2px solid ${config.primaryColor}` : 'none'};
            border-radius: 14px;
            font-size: 14px;
            font-weight: 700;
            cursor: pointer;
            transition: all 0.3s ease;
            margin-top: 12px;
            text-transform: uppercase;
            letter-spacing: 1px;
            font-family: inherit;
        }
        
        .submit-btn:hover {
            transform: translateY(-3px);
            box-shadow: 0 20px 50px ${config.primaryColor}50;
        }

        .submit-btn:disabled {
            opacity: 0.7;
            cursor: not-allowed;
            transform: none;
        }
        
        .alert {
            padding: 18px 22px;
            border-radius: 14px;
            margin-bottom: 28px;
            text-align: center;
            font-weight: 600;
            border: 2px solid;
        }
        
        .alert-success {
            background: rgba(34, 197, 94, 0.12);
            border-color: rgba(34, 197, 94, 0.4);
            color: #22c55e;
        }
        
        .alert-error {
            background: rgba(239, 68, 68, 0.12);
            border-color: rgba(239, 68, 68, 0.4);
            color: #ef4444;
        }
        
        .required { color: ${config.accentColor}; }
    </style>
</head>
<body>
    <div class="form-container">
        <div class="header-section">
            <div class="form-icon">🚀</div>
            <h1 class="form-title">${config.formTitle}</h1>
            <p class="form-subtitle">${config.productTitle}</p>
        </div>
        
        <?php if ($success === true): ?>
            <div class="alert alert-success"><?php echo htmlspecialchars($message); ?></div>
        <?php elseif ($success === false): ?>
            <div class="alert alert-error"><?php echo htmlspecialchars($message); ?></div>
        <?php endif; ?>
        
        <form method="POST">
            <div class="form-group">
                <label for="name" class="form-label">Full Name <span class="required">*</span></label>
                <input type="text" class="form-input" id="name" name="WP_BUYER_NAME" placeholder="Enter your full name" required
                    value="<?php echo isset($_POST['WP_BUYER_NAME']) ? htmlspecialchars($_POST['WP_BUYER_NAME']) : ''; ?>">
            </div>

            <div class="form-group">
                <label for="email" class="form-label">Email Address <span class="required">*</span></label>
                <input type="email" class="form-input" id="email" name="WP_BUYER_EMAIL" placeholder="Enter your email address" required
                    value="<?php echo isset($_POST['WP_BUYER_EMAIL']) ? htmlspecialchars($_POST['WP_BUYER_EMAIL']) : ''; ?>">
            </div>

            <div class="form-group">
                <label for="product" class="form-label">Select Product <span class="required">*</span></label>
                <select name="WP_ITEM_NUMBER" class="form-select" id="product" required>
                    <option value="">Choose your product...</option>
${productsOptions}
                </select>
            </div>

            <button type="submit" name="submit_form" class="submit-btn">🚀 Complete Registration</button>
        </form>
    </div>
</body>
</html>`;
}
